import baseWorker, { HouseholdProgress as BaseHouseholdProgress } from './indexV3.js';
import { dashboardHtml } from './dashboard.js';

const te=new TextEncoder();
const td=new TextDecoder();
let jwksCache={url:'',expiresAt:0,keys:[]};

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
function b64urlBytes(value){const s=String(value||'').replace(/-/g,'+').replace(/_/g,'/');const padded=s+'='.repeat((4-s.length%4)%4);const raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function parseJwtPart(value){return JSON.parse(td.decode(b64urlBytes(value)));}
function teamDomain(env){const raw=String(env.ACCESS_TEAM_DOMAIN||'').trim().replace(/\/+$/,'');if(!raw)return'';return /^https:\/\//i.test(raw)?raw:`https://${raw}`;}
function audiences(payload){return Array.isArray(payload?.aud)?payload.aud:[payload?.aud].filter(Boolean);}
function allowedEmail(env,email){const allow=String(env.ACCESS_ALLOWED_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return !allow.length||allow.includes(String(email||'').toLowerCase());}
async function refreshJwks(url){const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error('access_jwks_unavailable');const data=await r.json();jwksCache={url,expiresAt:Date.now()+5*60*1000,keys:Array.isArray(data?.keys)?data.keys:[]};}
async function getJwk(team,kid){const url=`${team}/cdn-cgi/access/certs`,now=Date.now();if(jwksCache.url!==url||jwksCache.expiresAt<now)await refreshJwks(url);let key=jwksCache.keys.find(x=>x.kid===kid);if(key)return key;await refreshJwks(url);key=jwksCache.keys.find(x=>x.kid===kid);if(!key)throw new Error('jwt_key');return key;}
async function verifyAccess(request,env){const team=teamDomain(env),aud=String(env.ACCESS_AUD||'').trim();if(!team||!aud)return{ok:false,status:503,code:'dashboard_not_configured'};const token=request.headers.get('cf-access-jwt-assertion')||'';if(!token)return{ok:false,status:403,code:'access_required'};try{const parts=token.split('.');if(parts.length!==3)throw new Error('jwt_shape');const header=parseJwtPart(parts[0]),payload=parseJwtPart(parts[1]);if(header.alg!=='RS256'||!header.kid)throw new Error('jwt_header');if(payload.iss!==team)throw new Error('jwt_issuer');if(!audiences(payload).includes(aud))throw new Error('jwt_audience');const now=Math.floor(Date.now()/1000);if(!Number.isFinite(payload.exp)||payload.exp<=now)throw new Error('jwt_expired');if(payload.nbf&&payload.nbf>now+30)throw new Error('jwt_not_yet_valid');if(!allowedEmail(env,payload.email))throw new Error('email_not_allowed');const jwk=await getJwk(team,header.kid);const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const verified=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,b64urlBytes(parts[2]),te.encode(`${parts[0]}.${parts[1]}`));if(!verified)throw new Error('jwt_signature');return{ok:true,email:String(payload.email||'')};}catch{return{ok:false,status:403,code:'access_invalid'};}}
function nonce(){const a=new Uint8Array(18);crypto.getRandomValues(a);let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s);}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));}
async function bodyJson(request){if(!(request.headers.get('content-type')||'').toLowerCase().includes('application/json'))throw new Error('invalid_content_type');return request.json();}
function progressStub(env){return env.PROGRESS.getByName(String(env.HOUSEHOLD_OBJECT_NAME||'family-main'));}
async function internal(env,path,body={}){const r=await progressStub(env).fetch(`https://internal${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));return{r,data};}
async function dashboardRequest(request,env){const auth=await verifyAccess(request,env);if(!auth.ok)return json({ok:false,code:auth.code},auth.status);const url=new URL(request.url);if(request.method==='GET'&&(url.pathname==='/admin'||url.pathname==='/admin/')){const n=nonce(),html=dashboardHtml(n);return new Response(html,{status:200,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','content-security-policy':`default-src 'none'; script-src 'nonce-${n}'; style-src 'nonce-${n}'; connect-src 'self'; img-src 'none'; font-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'`,'referrer-policy':'no-referrer','x-content-type-options':'nosniff'}});}if(request.method==='GET'&&url.pathname==='/admin/api/summary'){const x=await internal(env,'/internal/admin/dashboard-summary');return json(x.data,x.r.status);}if(request.method==='POST'&&url.pathname==='/admin/api/classify'){const b=await bodyJson(request),registrationId=String(b?.registrationId||''),status=String(b?.status||'');if(!uuid(registrationId)||!['production','ignored'].includes(status))return json({ok:false,code:'invalid_classification'},400);const x=await internal(env,'/internal/admin/classify',{registrationId,status,historyMode:'all',now:new Date().toISOString()});return json(x.data,x.r.status);}if(request.method==='POST'&&url.pathname==='/admin/api/revoke'){const b=await bodyJson(request),registrationId=String(b?.registrationId||'');if(!uuid(registrationId))return json({ok:false,code:'invalid_registration_id'},400);const x=await internal(env,'/internal/admin/revoke',{registrationId,now:new Date().toISOString()});return json(x.data,x.r.status);}return json({ok:false,code:'not_found'},404);}
export default{async fetch(request,env,ctx){const path=new URL(request.url).pathname;if(path==='/admin'||path.startsWith('/admin/')){try{return await dashboardRequest(request,env);}catch(e){return json({ok:false,code:e?.message==='invalid_content_type'?'invalid_content_type':'dashboard_error'},e?.message==='invalid_content_type'?400:500);}}return baseWorker.fetch(request,env,ctx);}};
function safePayload(value){try{return JSON.parse(value||'{}')}catch{return{}}}
export class HouseholdProgress extends BaseHouseholdProgress{async fetch(request){const url=new URL(request.url);if(request.method==='POST'&&url.pathname==='/internal/admin/dashboard-summary'){const registrations=this.sql.exec(`SELECT id,created_at,last_seen_at,revoked_at,status,device_code,production_from,device_type,os_family,browser_family FROM registrations ORDER BY last_seen_at DESC`).toArray();const counts=this.sql.exec(`SELECT registration_id,COUNT(DISTINCT source_record_id) AS n FROM events GROUP BY registration_id`).toArray();const countMap=new Map(counts.map(x=>[String(x.registration_id),Number(x.n||0)]));const eventRows=this.sql.exec(`SELECT e.registration_id,e.source_record_id,e.revision,e.event_type,e.occurred_at,e.payload_json FROM events e JOIN registrations r ON r.id=e.registration_id WHERE r.status='production' AND (r.production_from IS NULL OR e.occurred_at>=r.production_from) ORDER BY e.registration_id,e.source_record_id,e.revision DESC`).toArray();const logical=[],seen=new Set();for(const row of eventRows){const key=`${row.registration_id}:${row.source_record_id}`;if(seen.has(key))continue;seen.add(key);logical.push({...row,payload:safePayload(row.payload_json)});}let lastLearningAt=null,latestExam=null;const years={};for(const row of logical){if(!lastLearningAt||String(row.occurred_at)>lastLearningAt)lastLearningAt=String(row.occurred_at);const year=String(row.payload?.year||'');if(/^20\d{2}$/.test(year)&&!years[year])years[year]='started';if(row.event_type==='exam_completed'){if(/^20\d{2}$/.test(year))years[year]='done';if(!latestExam||String(row.occurred_at)>latestExam.occurredAt)latestExam={occurredAt:String(row.occurred_at),year:year||null,score:row.payload?.score!=null&&Number.isFinite(Number(row.payload.score))?Number(row.payload.score):null,maxScore:row.payload?.maxScore!=null&&Number.isFinite(Number(row.payload.maxScore))?Number(row.payload.maxScore):null};}}const snapshots=this.sql.exec(`SELECT s.payload_json FROM snapshots s JOIN registrations r ON r.id=s.registration_id WHERE r.status='production' AND r.production_from IS NULL`).toArray();for(const row of snapshots){const p=safePayload(row.payload_json);for(const [year,count] of Object.entries(p.eventsByYear||{})){if(Number(count)>0&&!years[year])years[year]='started';}}const devices=registrations.map(r=>({registrationId:String(r.id),deviceCode:r.device_code||null,osFamily:r.os_family||null,browserFamily:r.browser_family||null,status:r.revoked_at?'revoked':String(r.status||'unclassified'),lastSeenAt:r.last_seen_at||null,eventCount:countMap.get(String(r.id))||0}));return json({ok:true,progress:{lastLearningAt,latestExam,recordCount:logical.length,years},devices});}return super.fetch(request);}}
