import worker, { HouseholdProgress as BaseHouseholdProgress } from './indexV2.js';

const UNCLASSIFIED_DAILY_EVENT_BUDGET=10000;
const UNCLASSIFIED_TOTAL_EVENT_CAP=50000;
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
export default worker;
export class HouseholdProgress extends BaseHouseholdProgress {
  async fetch(request){
    const url=new URL(request.url);
    if(request.method==='POST' && url.pathname==='/internal/events'){
      const body=await request.json().catch(()=>null);if(!body)return json({ok:false,code:'invalid_json'},400);
      const registration=this.reg(body.credentialHash);if(!registration || registration.revoked_at)return json({ok:false,code:'unauthorized'},401);if(registration.status==='ignored')return json({ok:false,code:'collection_disabled'},403);
      const day=String(body.now||'').slice(0,10),dayStart=`${day}T00:00:00.000Z`;const today=this.sql.exec('SELECT COUNT(*) AS n FROM events WHERE registration_id=? AND received_at>=?',registration.id,dayStart).toArray()[0]?.n||0;const accepted=[],duplicate=[],rejected=[],pending=[],pendingByIdentity=new Map();
      for(const event of body.events||[]){const identity=JSON.stringify([event.appId,event.sourceRecordId,event.revision]);const inBatch=pendingByIdentity.get(identity);if(inBatch){inBatch.semanticHash===event.semanticHash?duplicate.push(event.eventId):rejected.push({eventId:event.eventId,code:'event_identity_conflict'});continue;}const existing=this.sql.exec('SELECT event_id,semantic_hash FROM events WHERE registration_id=? AND app_id=? AND source_record_id=? AND revision=? LIMIT 1',registration.id,event.appId,event.sourceRecordId,event.revision).toArray()[0];if(existing){existing.semantic_hash===event.semanticHash?duplicate.push(event.eventId):rejected.push({eventId:event.eventId,code:'event_identity_conflict'});continue;}pendingByIdentity.set(identity,event);pending.push(event);}
      if(today+pending.length>2000)return json({ok:false,code:'event_rate_limited',retryable:true},429);
      if(registration.status==='unclassified'){const unclassifiedToday=this.sql.exec(`SELECT COUNT(*) AS n FROM events e JOIN registrations r ON r.id=e.registration_id WHERE r.status='unclassified' AND r.revoked_at IS NULL AND e.received_at>=?`,dayStart).toArray()[0]?.n||0;const unclassifiedTotal=this.sql.exec(`SELECT COUNT(*) AS n FROM events e JOIN registrations r ON r.id=e.registration_id WHERE r.status='unclassified' AND r.revoked_at IS NULL`).toArray()[0]?.n||0;if(unclassifiedToday+pending.length>UNCLASSIFIED_DAILY_EVENT_BUDGET || unclassifiedTotal+pending.length>UNCLASSIFIED_TOTAL_EVENT_CAP)return json({ok:false,code:'unclassified_event_budget_limited',retryable:true},429);}
      for(const event of pending){const storedId=`${registration.id}:${event.eventId}`;this.sql.exec('INSERT INTO events(event_id,registration_id,app_id,source_record_id,revision,event_type,occurred_at,received_at,semantic_hash,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?)',storedId,registration.id,event.appId,event.sourceRecordId,event.revision,event.eventType,event.occurredAt,body.now,event.semanticHash,event.payloadJson);accepted.push(event.eventId);}this.touch(registration.id,body.now);return json({ok:true,accepted,duplicate,rejected});
    }
    if(request.method==='POST' && url.pathname==='/internal/admin/summary'){
      const registrations=this.sql.exec('SELECT id,created_at,last_seen_at,revoked_at,status,device_code,production_from,device_type,os_family,browser_family FROM registrations ORDER BY created_at').toArray();const apps=this.sql.exec('SELECT app_id,COUNT(DISTINCT registration_id||":"||source_record_id) AS record_count,COUNT(*) AS revision_count,MAX(received_at) AS last_received_at FROM events GROUP BY app_id ORDER BY app_id').toArray();const productionApps=this.sql.exec(`SELECT e.app_id,COUNT(DISTINCT e.registration_id||':'||e.source_record_id) AS record_count,COUNT(DISTINCT e.registration_id||':'||e.source_record_id||':'||e.revision) AS revision_count,MAX(e.received_at) AS last_received_at FROM events e JOIN registrations r ON r.id=e.registration_id WHERE r.status='production' AND (r.production_from IS NULL OR e.occurred_at>=r.production_from) GROUP BY e.app_id ORDER BY e.app_id`).toArray();const snapshots=this.sql.exec('SELECT registration_id,app_id,generation,updated_at,payload_json FROM snapshots ORDER BY updated_at DESC').toArray().map(row=>({...row,payload:JSON.parse(row.payload_json)}));const productionSnapshots=this.sql.exec(`SELECT s.registration_id,s.app_id,s.generation,s.updated_at,s.payload_json FROM snapshots s JOIN registrations r ON r.id=s.registration_id WHERE r.status='production' AND r.production_from IS NULL ORDER BY s.updated_at DESC`).toArray().map(row=>({...row,payload:JSON.parse(row.payload_json)}));return json({ok:true,registrations,apps,productionApps,snapshots,productionSnapshots});
    }
    return super.fetch(request);
  }
}
