import baseWorker, { HouseholdProgress as BaseHouseholdProgress } from './indexV4.js';
import { APP_CONFIG, APP_IDS, APP_ID_SET } from './platformConfig.js';

const MAX_BATCH=10;
const MAX_EVENT_BYTES=16*1024;
const MAX_SNAPSHOT_BYTES=32*1024;
const EVENT_FIELDS=new Set(['year','mode','kind','type','score','maxScore','correct','total','draftId','questionId','contentVersion','clockUnknown','step','level','category','skill','section','lesson','unit','completed','durationSec','accuracy','attempt','lastLearningAt']);
const SNAPSHOT_FIELDS=new Set(['baseline','eventCount','scoredEventCount','scoreTotal','eventsByYear','capturedAt','progressLabel','completedCount','totalCount']);
const te=new TextEncoder();
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});}
function normalizeOrigin(v){try{return new URL(v).origin}catch{return''}}
function allowedOrigins(env){return new Set(String(env.ALLOWED_ORIGINS||'https://fyam8.github.io').split(',').map(x=>normalizeOrigin(x.trim())).filter(Boolean));}
function cors(request,env){const o=normalizeOrigin(request.headers.get('origin')||'');if(!o||!allowedOrigins(env).has(o))return{};return{'access-control-allow-origin':o,'access-control-allow-headers':'authorization, content-type','access-control-allow-methods':'GET, POST, PUT, OPTIONS','access-control-max-age':'600','vary':'Origin'};}
function bearer(r){const m=/^Bearer\s+(.+)$/i.exec(r.headers.get('authorization')||'');return m?m[1].trim():'';}
async function parseJson(r){if(!(r.headers.get('content-type')||'').toLowerCase().includes('application/json'))throw new Error('content_type');return r.json();}
async function sha256Hex(v){const d=await crypto.subtle.digest('SHA-256',te.encode(String(v)));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function canonicalize(v){if(Array.isArray(v))return v.map(canonicalize);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])]));return v;}
const canonicalJson=v=>JSON.stringify(canonicalize(v));
const byteLength=v=>te.encode(typeof v==='string'?v:JSON.stringify(v)).byteLength;
function validPayloadShape(p,allowed){return p&&typeof p==='object'&&!Array.isArray(p)&&Object.keys(p).every(k=>allowed.has(k));}
function validOptionalString(p,k,max){return p[k]===undefined||(typeof p[k]==='string'&&p[k].length<=max);}
function validOptionalNumber(p,k){return p[k]===undefined||(typeof p[k]==='number'&&Number.isFinite(p[k])&&Math.abs(p[k])<=1e9);}
function validOptionalBoolean(p,k){return p[k]===undefined||typeof p[k]==='boolean';}
function validateEventPayload(p){if(!validPayloadShape(p,EVENT_FIELDS))return{ok:false,code:'payload_field_not_allowed'};for(const [k,max] of [['year',8],['mode',80],['kind',80],['type',80],['draftId',200],['questionId',200],['contentVersion',120],['category',120],['skill',120],['section',120],['lesson',120],['unit',120],['level',80],['step',80],['lastLearningAt',80]])if(!validOptionalString(p,k,max))return{ok:false,code:'invalid_payload_field'};for(const k of ['score','maxScore','correct','total','durationSec','accuracy','attempt'])if(!validOptionalNumber(p,k))return{ok:false,code:'invalid_payload_field'};for(const k of ['clockUnknown','completed'])if(!validOptionalBoolean(p,k))return{ok:false,code:'invalid_payload_field'};if(p.lastLearningAt!==undefined&&!Number.isFinite(Date.parse(p.lastLearningAt)))return{ok:false,code:'invalid_payload_field'};return{ok:true};}
function validateSnapshotPayload(p){if(!validPayloadShape(p,SNAPSHOT_FIELDS))return{ok:false,code:'payload_field_not_allowed'};if(p.baseline!==true)return{ok:false,code:'invalid_snapshot_payload'};if(!Number.isSafeInteger(p.eventCount)||p.eventCount<0||p.eventCount>1e7)return{ok:false,code:'invalid_snapshot_payload'};for(const k of ['scoredEventCount','completedCount','totalCount'])if(p[k]!==undefined&&(!Number.isSafeInteger(p[k])||p[k]<0||p[k]>1e7))return{ok:false,code:'invalid_snapshot_payload'};if(p.scoreTotal!==undefined&&(typeof p.scoreTotal!=='number'||!Number.isFinite(p.scoreTotal)||Math.abs(p.scoreTotal)>1e12))return{ok:false,code:'invalid_snapshot_payload'};if(typeof p.capturedAt!=='string'||!Number.isFinite(Date.parse(p.capturedAt)))return{ok:false,code:'invalid_snapshot_payload'};if(p.progressLabel!==undefined&&(typeof p.progressLabel!=='string'||p.progressLabel.length>160))return{ok:false,code:'invalid_snapshot_payload'};if(p.eventsByYear!==undefined){if(!p.eventsByYear||typeof p.eventsByYear!=='object'||Array.isArray(p.eventsByYear)||Object.keys(p.eventsByYear).length>50)return{ok:false,code:'invalid_snapshot_payload'};for(const [year,count] of Object.entries(p.eventsByYear))if(!/^\d{4}$/.test(year)||!Number.isSafeInteger(count)||count<0||count>1e7)return{ok:false,code:'invalid_snapshot_payload'};}return{ok:true};}
function validateEvent(raw){if(!raw||typeof raw!=='object')return{ok:false,code:'invalid_event'};const eventId=String(raw.eventId||'').trim(),appId=String(raw.appId||''),sourceRecordId=String(raw.sourceRecordId||'').trim(),revision=Number(raw.revision),eventType=String(raw.eventType||'').trim(),occurredAt=String(raw.occurredAt||''),payload=raw.payload&&typeof raw.payload==='object'&&!Array.isArray(raw.payload)?raw.payload:{};if(!eventId||eventId.length>200)return{ok:false,code:'invalid_event_id'};if(!APP_ID_SET.has(appId))return{ok:false,code:'app_not_allowed'};if(!sourceRecordId||sourceRecordId.length>200)return{ok:false,code:'invalid_source_record_id'};if(!Number.isSafeInteger(revision)||revision<1||revision>1000)return{ok:false,code:'invalid_revision'};if(!eventType||eventType.length>80)return{ok:false,code:'invalid_event_type'};if(!Number.isFinite(Date.parse(occurredAt)))return{ok:false,code:'invalid_occurred_at'};if(byteLength(payload)>MAX_EVENT_BYTES)return{ok:false,code:'event_too_large'};const payloadCheck=validateEventPayload(payload);if(!payloadCheck.ok)return payloadCheck;return{ok:true,value:{eventId,appId,sourceRecordId,revision,eventType,occurredAt,payload}};}
function validateSnapshot(raw){if(!raw||typeof raw!=='object')return{ok:false,code:'invalid_snapshot'};const appId=String(raw.appId||''),generation=Number(raw.generation),payload=raw.payload&&typeof raw.payload==='object'&&!Array.isArray(raw.payload)?raw.payload:{};if(!APP_ID_SET.has(appId))return{ok:false,code:'app_not_allowed'};if(!Number.isSafeInteger(generation)||generation<1)return{ok:false,code:'invalid_generation'};if(byteLength(payload)>MAX_SNAPSHOT_BYTES)return{ok:false,code:'snapshot_too_large'};const payloadCheck=validateSnapshotPayload(payload);if(!payloadCheck.ok)return payloadCheck;return{ok:true,value:{appId,generation,payload}};}
function progressStub(env){return env.PROGRESS.getByName(String(env.HOUSEHOLD_OBJECT_NAME||'family-main'));}
async function internal(env,path,body){const r=await progressStub(env).fetch(`https://internal${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{response:r,data:await r.json().catch(()=>({}))};}
export default{async fetch(request,env,ctx){const url=new URL(request.url),ch=cors(request,env);if(request.method==='GET'&&url.pathname==='/health')return json({ok:true,service:'waseshibu-progress-api',platform:'WaseShibu Progress Platform',supportedApps:APP_IDS,time:new Date().toISOString()},200,ch);try{if(request.method==='POST'&&url.pathname==='/v1/events/batch'){if(!Object.keys(ch).length)return json({ok:false,code:'origin_forbidden'},403);const token=bearer(request);if(!token)return json({ok:false,code:'unauthorized'},401,ch);const b=await parseJson(request),incoming=Array.isArray(b?.events)?b.events:[];if(!incoming.length||incoming.length>MAX_BATCH)return json({ok:false,code:'invalid_batch_size'},400,ch);const events=[],rejected=[];for(const raw of incoming){const c=validateEvent(raw);if(!c.ok){rejected.push({eventId:String(raw?.eventId||''),code:c.code});continue;}const semanticHash=await sha256Hex(canonicalJson({appId:c.value.appId,sourceRecordId:c.value.sourceRecordId,revision:c.value.revision,eventType:c.value.eventType,occurredAt:c.value.occurredAt,payload:c.value.payload}));events.push({...c.value,payloadJson:canonicalJson(c.value.payload),semanticHash});}if(!events.length)return json({ok:false,code:'no_valid_events',rejected},400,ch);const x=await internal(env,'/internal/events',{credentialHash:await sha256Hex(token),events,now:new Date().toISOString()});if(!x.response.ok)return json(x.data,x.response.status,ch);return json({...x.data,rejected:[...(x.data.rejected||[]),...rejected]},200,ch);}if(request.method==='PUT'&&url.pathname==='/v1/progress/snapshot'){if(!Object.keys(ch).length)return json({ok:false,code:'origin_forbidden'},403);const token=bearer(request);if(!token)return json({ok:false,code:'unauthorized'},401,ch);const c=validateSnapshot(await parseJson(request));if(!c.ok)return json({ok:false,code:c.code},400,ch);const x=await internal(env,'/internal/snapshot',{credentialHash:await sha256Hex(token),snapshot:{...c.value,payloadJson:canonicalJson(c.value.payload)},now:new Date().toISOString()});return json(x.data,x.response.status,ch);}}catch(e){return json({ok:false,code:e?.message==='content_type'?'invalid_content_type':'server_error'},e?.message==='content_type'?400:500,ch);}return baseWorker.fetch(request,env,ctx);}};
function safePayload(value){try{return JSON.parse(value||'{}')}catch{return{}}}
function emptyApp(appId){const cfg=APP_CONFIG[appId];return{appId,label:cfg.label,lastLearningAt:null,latestExam:null,recordCount:0,years:{},progressLabel:null};}
function applyEvent(app,row){app.recordCount++;if(!app.lastLearningAt||String(row.occurred_at)>app.lastLearningAt)app.lastLearningAt=String(row.occurred_at);const year=String(row.payload?.year||'');if(APP_CONFIG[app.appId].supportsYears&&/^20\d{2}$/.test(year)&&!app.years[year])app.years[year]='started';const yearCompleted=row.event_type==='exam_completed'||row.event_type==='year_completed';if(yearCompleted&&APP_CONFIG[app.appId].supportsYears&&/^20\d{2}$/.test(year))app.years[year]='done';if(row.event_type==='exam_completed'&&APP_CONFIG[app.appId].supportsExamScore&&(!app.latestExam||String(row.occurred_at)>app.latestExam.occurredAt))app.latestExam={occurredAt:String(row.occurred_at),year:year||null,score:row.payload?.score!=null&&Number.isFinite(Number(row.payload.score))?Number(row.payload.score):null,maxScore:row.payload?.maxScore!=null&&Number.isFinite(Number(row.payload.maxScore))?Number(row.payload.maxScore):null};}
function applySnapshot(app,p){if(APP_CONFIG[app.appId].supportsYears)for(const [year,count] of Object.entries(p.eventsByYear||{})){if(Number(count)>0&&!app.years[year])app.years[year]='started';}if(!app.progressLabel&&typeof p.progressLabel==='string')app.progressLabel=p.progressLabel;}
function appSet(){return Object.fromEntries(APP_IDS.map(id=>[id,emptyApp(id)]));}
export class HouseholdProgress extends BaseHouseholdProgress{async fetch(request){const url=new URL(request.url);if(request.method==='POST'&&url.pathname==='/internal/admin/dashboard-summary'){const registrations=this.sql.exec(`SELECT id,created_at,last_seen_at,revoked_at,status,device_code,production_from,device_type,os_family,browser_family FROM registrations ORDER BY last_seen_at DESC`).toArray();const registrationMap=new Map(registrations.map(r=>[String(r.id),r]));const deviceApps=new Map(registrations.map(r=>[String(r.id),appSet()]));
const allEventRows=this.sql.exec(`SELECT registration_id,app_id,source_record_id,revision,event_type,occurred_at,payload_json FROM events ORDER BY registration_id,app_id,source_record_id,revision DESC`).toArray();const allSeen=new Set();const formalApps=appSet();const formalSeen=new Set();for(const row of allEventRows){const registrationId=String(row.registration_id),appId=String(row.app_id);if(!APP_ID_SET.has(appId)||!registrationMap.has(registrationId))continue;const key=`${registrationId}:${appId}:${row.source_record_id}`;if(!allSeen.has(key)){allSeen.add(key);const parsed={...row,payload:safePayload(row.payload_json)};applyEvent(deviceApps.get(registrationId)[appId],parsed);}const reg=registrationMap.get(registrationId);const isFormal=String(reg.status||'unclassified')==='production'&&!reg.revoked_at&&(!reg.production_from||String(row.occurred_at)>=String(reg.production_from));if(isFormal&&!formalSeen.has(key)){formalSeen.add(key);applyEvent(formalApps[appId],{...row,payload:safePayload(row.payload_json)});}}
const snapshotRows=this.sql.exec(`SELECT registration_id,app_id,payload_json FROM snapshots`).toArray();for(const row of snapshotRows){const registrationId=String(row.registration_id),appId=String(row.app_id);if(!APP_ID_SET.has(appId)||!registrationMap.has(registrationId))continue;const p=safePayload(row.payload_json);applySnapshot(deviceApps.get(registrationId)[appId],p);const reg=registrationMap.get(registrationId);if(String(reg.status||'unclassified')==='production'&&!reg.revoked_at&&reg.production_from==null)applySnapshot(formalApps[appId],p);}
const devices=registrations.map(r=>{const registrationId=String(r.id),apps=APP_IDS.map(id=>deviceApps.get(registrationId)[id]);return{registrationId,deviceCode:r.device_code||null,deviceType:r.device_type||null,osFamily:r.os_family||null,browserFamily:r.browser_family||null,status:r.revoked_at?'revoked':String(r.status||'unclassified'),createdAt:r.created_at||null,lastSeenAt:r.last_seen_at||null,productionFrom:r.production_from||null,eventCount:apps.reduce((n,a)=>n+Number(a.recordCount||0),0),apps};});return json({ok:true,platform:'WaseShibu Progress Platform',apps:APP_IDS.map(id=>formalApps[id]),devices});}return super.fetch(request);}}
